source "https://supermarket.chef.io"
cookbook "hocaboo_api", path: "./hocaboo_api"
cookbook "initial_setup", path: "./initial_setup"
cookbook "newrelic-infra", path: "./newrelic-infra"
cookbook "php56_apache", path: "./php56_apache"
